FROM dpuerta/centos_epel_iso_java:7
MAINTAINER David Puerta Vera <puertavera@gmail.com>

RUN yum clean all \ 
&& yum install java-1.7.0-openjdk ImageMagick zip unzip rar unrar perl-Image-ExifTool -y \
$$ yum clean all \

